# 파비콘 설정
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 아바타 이미지
avatar:
  author_photo: /images/avatar.jpg
  author_nickname: Argon
  author_job: "@Backend-engineer"
  author_bio: "사소한 곳에 들이는 노력의 가치를 중요시하는 개발자, 배우고 도전하는 것을 좋아하는 모험가"
  author_email: "argon1025@gmail.com"
  author_job_place: "StageFive"
  path: /

# 대체 썸네일 구성, 기본 10개 이상
thumbnail:
  - url: /thumbnail/t1.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white
  - url: /thumbnail/t2.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white
  - url: /thumbnail/t3.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white
  - url: /thumbnail/t4.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white
  - url: /thumbnail/t5.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white
  - url: /thumbnail/t6.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white
  - url: /thumbnail/t7.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white
  - url: /thumbnail/t8.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white
  - url: /thumbnail/t9.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white
  - url: /thumbnail/t10.jpg
    auth: Photo by Pawel Czerwinski on Unsplash
    textColor: white

# Google GA설정
# https://analytics.google.com
gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

# 코멘트 구성
comments:
  enable: true
  disqus:
    # https://disqus.com/
    enable: true
    shortname: argon1025

# 메뉴 구성
navbar:
  - name: Index
    enable: true
    path: /
    key: home
  - name: Series
    enable: true
    path: /categories/
    key: categories
  - name: TechTag
    enable: true
    path: /tags/
    key: tags
  - name: Archive
    enable: true
    path: /archives/
    key: archives
  - name: Friends
    enable: false
    path: /friends/
    key: friends
  - name: About
    enable: false
    path: /about/
    key: about

# 게시글 이동 버튼 활성화
prevnext:
  enable: true

# 하단 설정
# 아이콘 FontAwesome -> fa-{icon} 형식만 지원
footer:
  social:
    - name: github
      icon: github
      path: https://github.com/argon1025
footerContent:
  copyright: Copyright © 2022 Argon1025

# 게시글 테크 아이콘 설정
# simple-icons :https://github.com/simple-icons/simple-icons/blob/master/slugs.md
icons:
  nodeJs:
    - type: simpleIcon
      name: nodedotjs